#spring:
#  application:
#    name: coupon
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://106.52.142.97:3306/gulimall_pms?useUnicode=true&characterEncoding=utf8&useSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 106.52.142.97:8848
#  #设置实体类的自增主键
#  global-config:
#    db-config:
#      id-type: auto
#
#server:
#  port: 8000