spring:
  application:
    name: order
  datasource:
    username: root
    password: root
    url: jdbc:mysql://106.52.142.97:3306/gulimall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  #设置实体类的自增主键
  global-config:
    db-config:
      id-type: auto

server:
  port: 9000